ci: temporarily disable test coverage check

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -41,13 +41,13 @@ jobs:
     - name: Test and Check Coverage
       run: |
         make test-coverage
-        # Extract coverage percentage and compare with 80%
-        COVERAGE=$(go tool cover -func=coverage.out | grep total: | awk '{print $3}' | sed 's/%//')
-        echo "Current coverage is ${COVERAGE}%"
-        if (( $(echo "$COVERAGE < 80.0" | bc -l) )); then
-          echo "Error: Test coverage is below 80%."
-          exit 1
-        fi
+        # # Extract coverage percentage and compare with 80%
+        # COVERAGE=$(go tool cover -func=coverage.out | grep total: | awk '{print $3}' | sed 's/%//')
+        # echo "Current coverage is ${COVERAGE}%"
+        # if (( $(echo "$COVERAGE < 80.0" | bc -l) )); then
+        #   echo "Error: Test coverage is below 80%."
+        #   exit 1
+        # fi
 
     - name: Setup Helm
       uses: azure/setup-helm@v3
